# Generated by Django 3.1.8 on 2022-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('username', models.CharField(max_length=99)),
                ('height', models.CharField(max_length=99)),
                ('weight', models.CharField(max_length=99)),
                ('eyes', models.CharField(max_length=99)),
                ('hair', models.CharField(max_length=99)),
                ('education', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('description', models.TextField()),
            ],
        ),
    ]
