# Generated by Django 3.1.8 on 2022-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('post_id', models.TextField()),
                ('comment', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
