# Generated by Django 3.1.8 on 2022-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_comment',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
