# Generated by Django 3.1.8 on 2022-01-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20220113_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('request_user_name', models.CharField(max_length=99)),
                ('request_name', models.CharField(max_length=99)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
