# Generated by Django 3.1.8 on 2022-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_friend_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='request_count',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
