# Generated by Django 3.1.8 on 2022-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20220114_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='only_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
