# Generated by Django 3.1.8 on 2022-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_friend_list_only_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_list',
            name='only_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
