# Generated by Django 3.1.8 on 2022-01-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20220115_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_list',
            name='only_date',
        ),
    ]
