# Generated by Django 3.1.8 on 2022-01-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_remove_friend_list_only_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('chat_user_name', models.CharField(max_length=99)),
                ('chat_name', models.CharField(max_length=99)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('only_date', models.DateField(auto_now_add=True)),
                ('friend_count', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
