# Generated by Django 3.1.8 on 2022-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
