# Generated by Django 3.1.8 on 2022-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20220123_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='cover.jpg', null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='photo/'),
        ),
    ]
