# Generated by Django 3.1.8 on 2022-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20220123_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='comment_count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='photo/cover.png', null=True, upload_to='photo/'),
        ),
    ]
